// Medical specialties enum matching backend
export const MEDICAL_SPECIALTIES = [
  "Allergist",
  "Immunologist",
  "Anesthesiologist",
  "Cardiologist",
  "Colon and Rectal Surgeon",
  "Dermatologist",
  "Radiologist",
  "Emergency Medicine Physician",
  "Endocrinologist",
  "Family Medicine Physician",
  "Gastroenterologist",
  "General Surgeon",
  "Geriatrician",
  "Hematologist",
  "Infectious Disease Specialist",
  "Internist",
  "Medical Geneticist",
  "Nephrologist",
  "Neurosurgeon",
  "Neurologist",
  "Nuclear Medicine Specialist",
  "Obstetrician-Gynecologist",
  "Oncologist",
  "Ophthalmologist",
  "Orthopedic Surgeon",
  "Otolaryngologist",
  "ENT Specialist",
  "Pathologist",
  "Pediatrician",
  "Physiatrist",
  "Plastic Surgeon",
  "Preventive Medicine Specialist",
  "Psychiatrist",
  "Pulmonologist",
  "Radiation Oncologist",
  "Rheumatologist",
  "Sleep Medicine Specialist",
  "Sports Medicine Specialist",
  "Urologist",
  "Vascular Surgeon",
] as const;

export type MedicalSpecialty = typeof MEDICAL_SPECIALTIES[number];

